apiVersion: v1
kind: Namespace
metadata:
  name: 5mapi-agrmtwrite1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: 5mapi-agrmtwrite1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: smapi-agrmtwrite1
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - name: http
      port: 80
      targetPort: 80



